spring.application.name=devflow
server.port=4000

spring.datasource.url=jdbc:postgresql://localhost:5432/dev-flow
spring.datasource.username=postgres
spring.datasource.password=#HDgD123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secret=your-super-secret-jwt-key-change-this-in-production
jwt.refresh-secret=your-super-secret-refresh-key-change-this-in-production
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000

app.env=development

logging.level.root=INFO
logging.level.com.devflow=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.output.ansi.enabled=ALWAYS

spring.jackson.property-naming-strategy=SNAKE_CASE